#!/usr/bin/env python3
"""Prove that the local scale coupling is generated by its own gradients."""

from __future__ import annotations

import json
from pathlib import Path
import sys

import sympy as sp


ROOT = Path(__file__).resolve().parents[1]
for value in (str(ROOT), str(ROOT / "src")):
    if value not in sys.path:
        sys.path.insert(0, value)

from recursive_horizons.evidence_io import canonical_json_bytes  # noqa: E402
from recursive_horizons.unified_action import SelfDualScaleCoupling  # noqa: E402


OUTPUT = ROOT / "results/nsc-1-s-one-field-coupling-closure.json"


def run() -> dict[str, object]:
    if OUTPUT.exists():
        raise RuntimeError("S-one field-coupling closure output already exists")
    f, m0, e0, a2, b2 = sp.symbols("f m_0 e_0 A_squared B_squared", positive=True)
    density = sp.Rational(1, 2) * (m0**2 * f**2 * a2 + b2 / (e0**2 * f**2))
    field_equation = sp.factor(sp.diff(density, f))
    solutions = sp.solve(sp.Eq(field_equation, 0), f)
    positive_solution = (b2 / (m0**2 * e0**2 * a2)) ** sp.Rational(1, 4)
    if positive_solution not in solutions:
        raise RuntimeError("positive coupling-field solution differs")
    long_term = sp.Rational(1, 2) * m0**2 * f**2 * a2
    topological_term = sp.Rational(1, 2) * b2 / (e0**2 * f**2)
    equality_residual = sp.simplify(
        (long_term - topological_term).subs(f, positive_solution)
    )
    stationary_density = sp.simplify(density.subs(f, positive_solution))
    hessian = sp.simplify(sp.diff(density, f, 2).subs(f, positive_solution))
    fixture = SelfDualScaleCoupling(
        long_gradient_norm_squared=9.0,
        topological_gradient_norm_squared=144.0,
        m0=2.0,
        e0=0.5,
    )
    result = {
        "artifact_id": "NSC-1-S-ONE-FIELD-COUPLING-CLOSURE",
        "schema": "NSC-1-S-ONE-FIELD-COUPLING-CLOSURE-v1",
        "classification": "local_fabric_coupling_is_the_stationary_output_of_the_gradients_it_couples",
        "source": {
            "paper": "Exact_Self_Dual_Skyrmions",
            "arxiv": "1704.04807",
            "equations": [11, 12, 13, 14, 15, 16],
            "status": "imported_self_dual_identity_embedded_as_S_one_scale_sector",
        },
        "one_density": {
            "formula": str(density),
            "coupling_field_equation": str(field_equation),
            "positive_solution": str(positive_solution),
            "equivalent_fixed_point": "f^4=B_squared/(m0^2*e0^2*A_squared)",
        },
        "it_equals_it": {
            "forward": "f_determines_the_weight_of_long_and_topological_gradients",
            "return": "those_gradient_norms_determine_f_by_its_own_Euler_Lagrange_equation",
            "equal_energy_residual": str(equality_residual),
            "stationary_density": str(stationary_density),
            "positive_coupling_hessian": str(hessian),
        },
        "public_fixture": {
            "A_squared": fixture.long_gradient_norm_squared,
            "B_squared": fixture.topological_gradient_norm_squared,
            "m0": fixture.m0,
            "e0": fixture.e0,
            "derived_f": fixture.f,
            "long_energy_density": fixture.long_energy_density,
            "topological_energy_density": fixture.topological_energy_density,
            "self_consistent": fixture.self_consistent,
        },
        "Theta_fixed_point_progress": {
            "local_scale_field_removed_from_free_parameters": True,
            "remaining_global_combinations": ["m0/e0_energy_normalization", "m0*e0_length_normalization"],
            "independent_local_coupling_profile_forbidden": True,
        },
        "gate": {
            "field_variation_generates_coupling": sp.simplify(
                field_equation.subs(f, positive_solution)
            )
            == 0,
            "paired_gradient_energies_equal": equality_residual == 0,
            "stationary_solution_is_positive": hessian.is_positive is True,
            "numeric_fixture_self_consistent": fixture.self_consistent,
        },
        "next_result": "use_one_energy_and_one_length_anchor_to_fix_m0_over_e0_and_m0_times_e0_then_solve_charge_and_spin_sectors_without_local_mass_inputs",
        "nonclaims": {
            "electron_charge_and_spin_derived": False,
            "global_normalizations_predicted": False,
            "complete_Theta_fixed": False,
            "cross_scale_holdout_opened": False,
        },
        "terminal": True,
    }
    if not all(result["gate"].values()):
        raise RuntimeError("S-one field-coupling closure gate failed")
    OUTPUT.write_bytes(canonical_json_bytes(result))
    return result


def main() -> int:
    result = run()
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
