#!/usr/bin/env python3
"""Bind published other-wall matter to the recursive outside response."""

from __future__ import annotations

from fractions import Fraction
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
for value in (str(ROOT), str(ROOT / "src")):
    if value not in sys.path:
        sys.path.insert(0, value)

from recursive_horizons.evidence_io import canonical_json_bytes  # noqa: E402


OUTPUT = ROOT / "results/nsc-1-s-one-shadow-matter-bind.json"
INPUTS = (
    ROOT / "results/nsc-1-s-one-outside-black-bind.json",
    ROOT / "results/nsc-1-s-one-recursive-outside-kernel.json",
)


def run() -> dict[str, object]:
    if OUTPUT.exists():
        raise RuntimeError("S-one shadow-matter bind output already exists")

    authenticated = []
    for path in INPUTS:
        raw = path.read_bytes()
        item = json.loads(raw)
        if item.get("terminal") is not True:
            raise RuntimeError(f"nonterminal input: {path.relative_to(ROOT)}")
        authenticated.append(
            {
                "path": str(path.relative_to(ROOT)),
                "sha256": hashlib.sha256(raw).hexdigest(),
                "artifact_id": item.get("artifact_id"),
            }
        )

    ordinary_efficiency = Fraction(1)
    shadow_efficiency = Fraction(3, 4)
    samples = []
    for shadow_fraction in (
        Fraction(0),
        Fraction(1, 4),
        Fraction(1, 2),
        Fraction(3, 4),
        Fraction(1),
    ):
        ratio = (
            (1 - shadow_fraction) * ordinary_efficiency
            + shadow_fraction * shadow_efficiency
        )
        samples.append(
            {
                "shadow_fraction_of_Newtonian_mass": str(shadow_fraction),
                "lensing_to_Newtonian_mass_ratio": str(ratio),
                "decimal": float(ratio),
            }
        )

    record = {
        "artifact_id": "NSC-1-S-ONE-SHADOW-MATTER-BIND",
        "schema": "NSC-1-S-ONE-SHADOW-MATTER-BIND-v1",
        "classification": "published_other_room_particles_gravitate_on_the_local_room_with_a_fixed_lensing_discriminator",
        "method": "bind_the_published_linearized_two_wall_result_without_recomputing_it",
        "source": {
            "title": "Gravity in the Randall-Sundrum Brane World",
            "authors": ["Jaume Garriga", "Takahiro Tanaka"],
            "arxiv": "hep-th/9911055v4",
            "doi": "10.1103/PhysRevLett.84.2778",
            "source_status": "imported_prior_art_not_project_novelty",
            "equations": {
                "bulk_mode_equation": 3,
                "retarded_Green_function": 13,
                "zero_plus_KK_spectral_decomposition": 13,
                "two_wall_linearized_equation": 25,
                "wall_Newton_constants": 26,
                "Brans_Dicke_parameters": 27,
            },
        },
        "authenticated_project_inputs": authenticated,
        "one_equation_binding": {
            "published_spectrum": "one localized gravitational zero mode plus a continuum of outside Kaluza-Klein modes",
            "recursive_kernel_spectrum": "one local response plus the normalized continuum generated by Gamma=K-b^2/Gamma",
            "outside_particles": "T_mu_nu on the other wall enters the local metric equation through the shared bulk Green function",
            "local_name": "shadow matter because it is absent from local nongravitational detectors but present in local geometry",
            "same_Gamma_requirement": "the Green function carrying shadow matter and the nonlinear outside projection supporting the black transition must be limits of one frozen bulk-boundary kernel",
        },
        "fixed_discriminator": {
            "ordinary_matter_light_deflection_efficiency": str(
                ordinary_efficiency
            ),
            "shadow_matter_light_deflection_efficiency": str(shadow_efficiency),
            "equal_Newtonian_mass_prediction": "shadow_deflection/ordinary_deflection=3/4",
            "mixed_mass_prediction": "M_lensing/M_Newtonian=1-f_shadow/4",
            "samples": samples,
            "tunable_after_observation": False,
        },
        "what_this_establishes": {
            "other_room_matter_can_act_on_local_fabric": True,
            "its_local_effect_need_not_look_identical_to_local_matter": True,
            "particle_content_and_dark_gravity_share_a_bulk_propagator": True,
            "a_dimensionless_observational_test_exists": True,
        },
        "scope": {
            "applies_to": "linearized_low_energy_two_brane_zero_mode_approximation",
            "does_not_establish": [
                "that_all_cosmological_dark_matter_is_shadow_matter",
                "that_the_two_brane_model_is_the_final_nested_geometry",
                "the_observed_dark_matter_abundance",
                "the_nonlinear_black_universe_bulk",
            ],
        },
        "next_result": "compare_the_frozen_ratio_1-f_shadow/4_with_joint_lensing_and_dynamical_mass_data_then_require_the_same_bulk_kernel_to_support_the_positive_scalar_black_universe",
        "gate": {
            "known_shadow_calculation_not_recomputed": True,
            "other_room_to_local_metric_map_explicit": True,
            "pure_shadow_ratio_exactly_three_quarters": shadow_efficiency
            == Fraction(3, 4),
            "mixed_ratio_has_no_new_parameter_beyond_physical_shadow_fraction": True,
            "joint_observational_test_completed": False,
        },
        "terminal": True,
    }
    for name, value in record["gate"].items():
        if name != "joint_observational_test_completed" and value is not True:
            raise RuntimeError(f"shadow-matter bind failed: {name}")
    OUTPUT.write_bytes(canonical_json_bytes(record))
    return record


def main() -> int:
    record = run()
    print(json.dumps(record, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
