"""Recursive zero-tadpole normalization for the common NSC action.

The law removes the homogeneous local a0 metric source after the full
same-action assembly.  It is a finite renormalization condition motivated by
the relational-room postulate, not a cancellation inferred from the raw
spectral trace.  Derivative, gauge, boundary and topology-dependent nonlocal
terms are retained.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from math import pi

import numpy as np

from .nsc_mmp_embedding import CommonCoefficients


@dataclass(frozen=True)
class RelationalVacuumResult:
    raw: CommonCoefficients
    normalized: CommonCoefficients
    reference: str
    independent_coefficient_added: bool

    def to_dict(self):
        return {
            "raw": asdict(self.raw),
            "normalized": asdict(self.normalized),
            "reference": self.reference,
            "independent_coefficient_added": self.independent_coefficient_added,
        }


class RelationalVacuumNormalization:
    """Project out the local a0/zero-graviton-momentum tadpole in every room.

    P0(V,A,C)=(V,0,0), N=I-P0.  Requiring an unlinked homogeneous room to
    have zero metric source fixes the subtraction coefficient to the V
    generated by that same complete action at fixed internal spectral data.
    A finite Casimir/link remainder is not part of this projector.  No
    independent number enters.
    """

    reference = "unlinked homogeneous room in inherited dimensionless units"

    def normalize(self, coefficients: CommonCoefficients) -> RelationalVacuumResult:
        return RelationalVacuumResult(
            raw=coefficients,
            normalized=CommonCoefficients(
                einstein=coefficients.einstein,
                gauge=coefficients.gauge,
                vacuum=0.0,
            ),
            reference=self.reference,
            independent_coefficient_added=False,
        )

    @staticmethod
    def counterterm(vacuum_density: float, volume: float) -> float:
        if not np.isfinite(vacuum_density) or not np.isfinite(volume) or volume <= 0:
            raise ValueError("finite vacuum density and positive finite volume required")
        return float(-vacuum_density * volume)

    @classmethod
    def ctp_counterterm(
        cls, vacuum_density: float, volume_plus: float, volume_minus: float
    ) -> float:
        return cls.counterterm(vacuum_density, volume_plus) - cls.counterterm(
            vacuum_density, volume_minus
        )

    @staticmethod
    def scale_covariance_defect(
        vacuum_density: float, volume: float, omega: float, dimension: int = 4
    ) -> float:
        if (not np.isfinite(omega) or omega <= 0 or isinstance(dimension, bool)
                or not isinstance(dimension, int) or dimension < 1):
            raise ValueError("positive scale and dimension required")
        before = vacuum_density * volume
        after = omega**dimension * vacuum_density * volume / omega**dimension
        return float(after - before)

    @staticmethod
    def mmp_gate(coefficients: CommonCoefficients, flux: int = 1):
        raw = coefficients.mmp_map(flux)
        normalized = CommonCoefficients(
            coefficients.einstein, coefficients.gauge, 0.0
        ).mmp_map(flux)
        return {
            "raw": raw,
            "normalized": normalized,
            "Einstein_coefficient_unchanged": normalized["G_N"] == raw["G_N"],
            "gauge_coefficient_unchanged": normalized["g_squared"] == raw["g_squared"],
            "charge_radius_unchanged": normalized["r_e_squared"] == raw["r_e_squared"],
            "throat_length_unchanged": normalized["ell_MMP"] == raw["ell_MMP"],
            "vacuum_seed_Xi": normalized["Xi"],
            "charged_seed_bound_passes": normalized["Xi"] <= flux * flux / 4,
            "asymptotically_flat_bulk_vacuum_passes": normalized["lambda_4"] == 0,
        }


def coefficient_projector_matrix():
    """Return P0 and N on the local coefficient vector (V,A,C)."""
    p0 = np.diag([1.0, 0.0, 0.0])
    return p0, np.eye(3) - p0


def uniqueness_residual():
    """Linear-basis proof that the stated requirements uniquely give I-P0."""
    p0, normalization = coefficient_projector_matrix()
    return {
        "P0_idempotence": float(np.linalg.norm(p0 @ p0 - p0)),
        "normalization_idempotence": float(
            np.linalg.norm(normalization @ normalization - normalization)
        ),
        "zero_derivative_annihilated": float(
            np.linalg.norm(normalization @ np.array([1.0, 0.0, 0.0]))
        ),
        "Einstein_basis_preserved": float(
            np.linalg.norm(normalization @ np.array([0.0, 1.0, 0.0])
                           - np.array([0.0, 1.0, 0.0]))
        ),
        "gauge_basis_preserved": float(
            np.linalg.norm(normalization @ np.array([0.0, 0.0, 1.0])
                           - np.array([0.0, 0.0, 1.0]))
        ),
        "trace": float(np.trace(normalization)),
        "expected_trace": 2.0,
        "MMP_action_normalization": "G_N=1/(16*pi*A), g^2=1/(4*C)",
        "pi_control": pi,
    }
