"""Repository-check domain module; generated by a mechanical split."""

from __future__ import annotations

from ._shared import *  # noqa: F401,F403
from ._shared import (
    LINK_PATTERN,
    Path,
    REPOSITORY,
    REQUIRED,
    canonical_files,
    re,
    subprocess,
    unquote,
)


def check_required() -> list[str]:
    return [f"missing required file: {name}" for name in REQUIRED if not (REPOSITORY / name).is_file()]


def check_links() -> list[str]:
    failures: list[str] = []
    for source in REPOSITORY.rglob("*.md"):
        text = source.read_text(encoding="utf-8")
        for match in LINK_PATTERN.finditer(text):
            raw = match.group(1).strip()
            if raw.startswith("<") and raw.endswith(">"):
                raw = raw[1:-1]
            # Drop an optional Markdown link title after a whitespace separator.
            target = raw.split(maxsplit=1)[0]
            if target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            path_text = unquote(target.split("#", 1)[0])
            if not path_text:
                continue
            destination = (source.parent / path_text).resolve()
            if not destination.exists():
                relative = source.relative_to(REPOSITORY)
                failures.append(f"broken local link in {relative}: {target}")
    return failures


def check_public_text() -> list[str]:
    failures: list[str] = []
    forbidden = {
        "github.com/OWNER": "unresolved repository-owner placeholder",
        "/Users/admin/": "developer-specific absolute path",
        "machine-precision validation": "retired overclaim",
    }
    for path in canonical_files():
        if path.resolve() == Path(__file__).resolve():
            continue
        if path.suffix.lower() not in {".md", ".toml", ".cff", ".py", ".bib"}:
            continue
        text = path.read_text(encoding="utf-8")
        for phrase, explanation in forbidden.items():
            if phrase in text:
                # The README and ledger may name a retired phrase while explicitly
                # documenting its retirement.  Only placeholders/paths are global.
                if phrase == "machine-precision validation" and path.name in {
                    "README.md",
                    "claim-ledger.md",
                    "review-summary.md",
                }:
                    continue
                failures.append(
                    f"{path.relative_to(REPOSITORY)}: {explanation}: {phrase!r}"
                )
    return failures


SLIMMED_PUBLIC_SURFACES = frozenset(
    {
        "README.md",
        "docs/finite-gradient-closure.md",
        "docs/epistemic-status.md",
        "docs/review-summary.md",
        "paper/recursive-horizons.md",
        "paper/fgc-local-defocusing/README.md",
    }
)

# Stable owning-document contracts. Historical artifact chronologies belong to
# the claim ledger, catalog, changelog, and Git history, not these surfaces.
PHASE_MINUS1_REQUIRED_PHRASES: dict[str, tuple[str, ...]] = {
    "PLAN.md": (
        "1. `AGENTS.md` — creative research orientation.",
        "2. `docs/claim-ledger.md` — atomic scientific claims, evidence states, and falsifiers.",
        "3. `docs/research-roadmap.md` — forward dependency/execution plan.",
        "4. `docs/fgc-runtime-matrix.md` — runtime, environment, arithmetic, and raw/compact ownership.",
        "5. `results/README.md` — compact machine-result index.",
        "6. `paper/recursive-horizons.md` — versioned prospectus, not a live development log.",
        "7. `README.md` — short project entrypoint and routing page only.",
    ),
    "AGENTS.md": (
        # The protected user's creative document is not a machine certificate.
        # Check its research boundary, not an exact user-owned metadata label.
        "The following notation is not presented as a completed theory.",
        "not as an advocate trying to force a predetermined answer",
    ),
    "README.md": (
        "[Finite Gradient Closure](docs/finite-gradient-closure.md)",
        "[Nested Gradient Spectrum](docs/nested-gradient-spectrum.md)",
        "FGC-1-TDG10-QA2-PREF1",
        "No production temporal successor is selected",
        "or physical claim is",
        "mutate a terminal store, or run without a new committed",
        "Do not invoke a `run-*`",
        "[Claim ledger](docs/claim-ledger.md)",
        "[Research roadmap](docs/research-roadmap.md)",
        "permission to publish, release, submit, push, or contact anyone externally",
    ),
    "docs/claim-ledger.md": (
        "| C67 | **Finite Gradient Closure.",
        "| C71 | **Nested Gradient Spectrum.",
        "| C79 | **NGS-0.**",
        "| C80 | **DSF-3 finite-domain causal calibration.**",
        "| C84 | **No unaccountable explanatory variable.**",
        "| C231 | **FGC-1-TDG10-QA1-PREF1.**",
        "| C233 | **FGC-1-TDG10-QA2-PREF1.**",
        "compact SHA-256 `3a107bcede",
        "compact SHA-256 `08f88f02966ea5936e417a3a6a2c583e11783341a3d76f4ef5dc821e992691f6`",
        "QA1_raw_result_independently_bound=true",
        "QA2_PREF1_compact_result_present=true",
        "successor_remedy_selected=false",
        "state_advance_authorized=false",
        "physical claim remains false",
        "nonpromotion controls",
    ),
    "docs/research-roadmap.md": (
        "This is **FGC-2-SF1**",
        "No production temporal successor has been selected",
        "state-advancing attempt",
        "FGC-1-TDG11-MSEL1-FRZ1",
        "observed order `p >= 3/2`",
        "Neither statement implies a global transition",
        "No push, publication",
        "Produce an independently reproducible, constraint-controlled, finite-state,",
    ),
    "docs/finite-gradient-closure.md": (
        "**Finite Gradient Closure.** Whenever gravitational localization steepens",
        "completed physical infinity",
        "unbounded process",
        "hypothesis to implement and test",
        "Current programme routing",
        "[claim ledger](claim-ledger.md)",
        "[research roadmap](research-roadmap.md)",
        "components, causal calibration, particle inheritance, complexity",
    ),
    "docs/nested-gradient-spectrum.md": (
        "Nested Gradient Spectrum (NGS)",
        "not an identification of dark matter, dark energy",
        "The golden ratio is a possible eigenvalue, not a premise",
        "NGS-0 executable control",
        "Relational dark-sector posture: no unaccountable variable",
        "The familiar billiard-ball picture is an introductory approximation",
    ),
    "docs/epistemic-status.md": (
        "owns the labels and review rules, not the artifact chronology",
        "### E — Established input",
        "### O — Observation or published constraint",
        "### D — Repository derivation",
        "### H — Hypothesis or model postulate",
        "### A — Analogy or interpretation",
        "### N — Negative, null, or invalidated result",
        "### R — Retired claim",
        "### Q — Open question",
        "**no unaccountable explanatory variable**",
        "## Open-minded without madness",
    ),
    "docs/review-summary.md": (
        "dated historical audit",
        "archive/reviews/review-summary-2026-08-21.md",
        "not the current repository-status",
        "[Claim ledger](claim-ledger.md)",
        "[Research roadmap](research-roadmap.md)",
    ),
    "paper/recursive-horizons.md": (
        "Finite Gradient Closure",
        "## RH-0: Finite Gradient Closure",
        "Nested Gradient Spectrum",
        "NGS-0",
        "lower closure and an upper closure or finite handoff",
        "we see things for what they truly are",
        "open-minded without madness",
        "no unaccountable explanatory variable",
        "**Live development routing.**",
        "[claim ledger](../docs/claim-ledger.md)",
        "[research roadmap](../docs/research-roadmap.md)",
    ),
    "paper/fgc-local-defocusing/README.md": (
        "pre-result workspace",
        "FGC-1-TDG10-QA2-PREF1",
        "It selects no successor",
        "before any new state advance",
        "physical transition",
        "[claim ledger](../../docs/claim-ledger.md)",
        "[research roadmap](../../docs/research-roadmap.md)",
    ),
}

HISTORICAL_CHRONOLOGY_TOKENS = (
    "FGC-1-PRO18-FRZ1",
    "FGC-1-PRO18-PREF26",
    "FGC-1-PRO18-AUTH1",
    "FGC-1-HLT15-GEN1",
    "FGC-1-PRO18-PREF27",
    "FGC-1-PRO19-CFL1-FRZ1",
    "FGC-1-HLT14-MON14",
    "FGC-1-PRO17-PREF25",
    "72=4+6+18+44",
    "6277b3be",
    "five finite accepted",
)


def _read_public_surface(relative: str) -> str:
    return (REPOSITORY / relative).read_text(encoding="utf-8")


def _require_surface_phrases(
    relative: str,
    phrases: tuple[str, ...],
    failures: list[str],
) -> None:
    try:
        content = _read_public_surface(relative)
    except OSError as exc:
        failures.append(f"cannot read framework surface {relative}: {exc}")
        return
    for phrase in phrases:
        if phrase not in content:
            failures.append(
                f"{relative}: missing Phase -1 authority-boundary phrase {phrase!r}"
            )


def check_fgc_alignment() -> list[str]:
    """Keep FGC, NGS, and Phase -1 authority-boundary contracts canonical."""

    failures: list[str] = []
    for relative, phrases in PHASE_MINUS1_REQUIRED_PHRASES.items():
        _require_surface_phrases(relative, phrases, failures)
    return failures


def check_git_data_boundary() -> list[str]:
    failures: list[str] = []
    inside_git = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        cwd=REPOSITORY,
        capture_output=True,
        text=True,
    )
    if inside_git.returncode != 0:
        ignore_lines = {
            line.strip()
            for line in (REPOSITORY / ".gitignore").read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        }
        if "collected-data/*.fits" not in ignore_lines:
            failures.append(".gitignore does not exclude collected-data/*.fits")
        return failures

    completed = subprocess.run(
        ["git", "ls-files", "--", "collected-data/*.fits"],
        cwd=REPOSITORY,
        check=True,
        capture_output=True,
        text=True,
    )
    if completed.stdout.strip():
        failures.append("large third-party FITS files are tracked by Git")
    for name in ("smica_2048.fits", "mask_common.fits"):
        checked = subprocess.run(
            ["git", "check-ignore", "-q", f"collected-data/{name}"],
            cwd=REPOSITORY,
        )
        if checked.returncode != 0:
            failures.append(f"collected-data/{name} is not covered by .gitignore")
    return failures


def check_reference_sequence() -> list[str]:
    manuscript = (REPOSITORY / "paper" / "recursive-horizons.md").read_text(encoding="utf-8")
    try:
        references = manuscript.split("# References\n", 1)[1]
    except IndexError:
        return ["manuscript has no References section"]
    numbers = [int(value) for value in re.findall(r"(?m)^(\d+)\. ", references)]
    if not numbers:
        return ["manuscript reference list is empty"]
    expected = list(range(1, max(numbers) + 1))
    failures = []
    if numbers != expected:
        failures.append("manuscript references are not a contiguous 1..N sequence")
    body = manuscript.split("# References\n", 1)[0]
    citations = [
        int(value)
        for group in re.findall(r"\[([0-9, ]+)\]", body)
        for value in group.replace(" ", "").split(",")
        if value
    ]
    missing = sorted(set(expected) - set(citations))
    out_of_range = sorted(set(citations) - set(expected))
    if missing:
        failures.append(f"references never cited in manuscript body: {missing}")
    if out_of_range:
        failures.append(f"out-of-range manuscript citations: {out_of_range}")
    return failures

__all__ = tuple(name for name in globals() if not name.startswith("__"))
