"""Authenticate and reproduce the OPEN research draft; never certify physics."""
from __future__ import annotations

from decimal import Decimal
import gzip
from hashlib import sha1, sha256
import io
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
import tarfile
import tempfile

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = Path('paper/local-gate-evidence')
SOURCE = Path('paper/local-gate-draft')
PDF = Path('paper/local-incoming-gate-draft.pdf')
ARCHIVE = Path('paper/local-incoming-gate-draft-source.tar.gz')
MANIFEST = Path('paper/local-gate-draft-manifest.json')
COMPONENTS = ('field_space_time', 'changed_history_UV_tail', 'baseline_low_subgap',
              'upstream', 'energy_interpolation', 'covered_regions', 'phase_value',
              'between_node', 'arithmetic')


def digest(data: bytes) -> str:
    return sha256(data).hexdigest()


def read_json(path: Path):
    return json.loads(path.read_text(encoding='utf-8'))


def safe_path(root: Path, name: str) -> Path:
    relative = PurePosixPath(name)
    if (not name or relative.is_absolute() or '..' in relative.parts
            or '\\' in name or ':' in name or relative.as_posix() != name):
        raise ValueError(f'unsafe path: {name}')
    path = root.joinpath(*relative.parts)
    if any(part.startswith('.') for part in relative.parts):
        raise ValueError(f'hidden path: {name}')
    if not path.resolve().is_relative_to(root.resolve()) or path.is_symlink():
        raise ValueError(f'path escapes snapshot: {name}')
    return path


def authenticate_snapshot(root: Path):
    snapshot = read_json(root / EVIDENCE / 'snapshot.json')
    if (snapshot.get('schema') != 'NSC-OPEN-DRAFT-SNAPSHOT-v1'
            or snapshot.get('status') != 'OPEN'
            or snapshot.get('complete_scientific_dependency_closure') is not False
            or not re.fullmatch('[0-9a-f]{40}', snapshot.get('lab_commit', ''))):
        raise ValueError('invalid OPEN snapshot contract')
    seen = set()
    for entry in snapshot['files']:
        name = entry['path']
        if name in seen:
            raise ValueError('duplicate snapshot path')
        seen.add(name)
        data = safe_path(root / EVIDENCE, name).read_bytes()
        if digest(data) != entry['sha256'] or len(data) != entry['bytes']:
            raise ValueError(f'evidence mismatch: {name}')
        if not re.fullmatch('[0-9a-f]{40}', entry.get('git_blob', '')):
            raise ValueError('missing source Git blob')
        if sha1(b'blob ' + str(len(data)).encode() + b'\0' + data).hexdigest() != entry['git_blob']:
            raise ValueError('source Git blob differs')
    actual = {p.relative_to(root / EVIDENCE).as_posix()
              for p in (root / EVIDENCE).rglob('*') if p.is_file()}
    if actual != seen | {'snapshot.json'}:
        raise ValueError('snapshot file inventory differs')
    return snapshot


def evidence_values(root: Path) -> str:
    """Presentation numbers from original records, with no new error bounds."""
    budget = read_json(root / EVIDENCE / 'results/development/nsc-ks-gate-budget-v4.json')
    reanchor = read_json(root / EVIDENCE / 'results/development/nsc-ks-gate-reanchor-v2.json')
    if set(budget['components']) != set(COMPONENTS):
        raise ValueError('nine-component contract changed')
    best = next(r for r in reanchor['rows']
                if r['profile_identity'] == reanchor['best_measured_profile_identity'])
    if sum(r['bound'] is None for r in budget['components'].values()) != 6:
        raise ValueError('draft snapshot status changed; review manuscript')

    def tex(value):
        mantissa, exponent = f'{Decimal(str(value)):.5E}'.split('E')
        return mantissa + r'\times10^{' + str(int(exponent)) + '}'

    lines = ['% Generated by scripts/local_gate_draft.py from locked OPEN records.']
    for label, value in zip(('N', 'Beta'), best['nodal_maxima']):
        lines.append(r'\newcommand{\DraftNodal' + label + '}{' + tex(value) + '}')
    labels = {'covered_regions': 'Covered', 'phase_value': 'Phase',
              'energy_interpolation': 'Interpolation'}
    for component, label in labels.items():
        for suffix, value in zip(('N', 'Beta'), budget['components'][component]['bound']):
            lines.append(r'\newcommand{\Draft' + label + suffix + '}{' + tex(value) + '}')
    # This is a displayed partial sum, not a directed scientific error producer.
    for index, suffix in enumerate(('N', 'Beta')):
        total = sum(Decimal(str(r['bound'][index])) for r in budget['components'].values()
                    if r['bound'] is not None)
        lines.append(r'\newcommand{\DraftPartial' + suffix + '}{' + tex(total) + '}')
    return '\n'.join(lines) + '\n'


def source_files(root: Path) -> dict[str, bytes]:
    expected = {'main.tex', 'references.bib', 'result_macros.tex', 'evidence_values.tex'}
    folder = root / SOURCE
    actual = {p.relative_to(folder).as_posix() for p in folder.rglob('*') if p.is_file()}
    if actual != expected:
        raise ValueError('unexpected or missing draft source files')
    files = {name: safe_path(folder, name).read_bytes() for name in sorted(expected)}
    if files['evidence_values.tex'] != evidence_values(root).encode('ascii'):
        raise ValueError('generated evidence values differ from records')
    text = files['main.tex'].decode('ascii')
    if any(token in text for token in (r'\write18', r'\openout', r'\includegraphics')):
        raise ValueError('unsupported external draft dependency')
    inputs = re.findall(r'\\input\s*\{([^}]+)\}', text)
    if set(inputs) != {'result_macros', 'evidence_values'}:
        raise ValueError('unexpected TeX input graph')
    for name in ('result_macros.tex', 'evidence_values.tex'):
        if re.search(r'\\(?:input|include|includegraphics)\b', files[name].decode('ascii')):
            raise ValueError('nested TeX inputs are not supported by this draft')
    macros = files['result_macros.tex'].decode('ascii')
    stamp = next(line.removeprefix('%% nsc-macros-json: ') for line in macros.splitlines()
                 if line.startswith('%% nsc-macros-json: '))
    payload = json.loads(stamp)
    if (payload['verdict'] != 'OPEN' or payload['submission_ready'] is not False
            or payload['mode'] != 'draft' or payload['recorded_certificate'] is not False
            or r'\newcommand{\NSCVerdict}{OPEN}' not in macros):
        raise ValueError('draft cannot carry a closed certificate')
    reanchor = read_json(root / EVIDENCE / 'results/development/nsc-ks-gate-reanchor-v2.json')
    if payload['profile_identity'] != reanchor['best_measured_profile_identity']:
        raise ValueError('macro profile differs from snapshot')
    return files


def packed_source(files: dict[str, bytes]) -> bytes:
    output = io.BytesIO()
    with gzip.GzipFile(fileobj=output, mode='wb', filename='', mtime=0) as gz:
        with tarfile.open(fileobj=gz, mode='w', format=tarfile.USTAR_FORMAT) as tar:
            for name, data in sorted(files.items()):
                if not re.fullmatch(r'[A-Za-z0-9_-]+\.(tex|bib|bbl)', name):
                    raise ValueError('unexpected archive member')
                info = tarfile.TarInfo(name)
                info.size, info.mode, info.mtime = len(data), 0o644, 0
                tar.addfile(info, io.BytesIO(data))
    return output.getvalue()


def compile_twice(files: dict[str, bytes]):
    tools = {name: shutil.which(name) for name in ('pdflatex', 'bibtex')}
    if not all(tools.values()):
        raise ValueError('draft build requires pdflatex and bibtex')
    env = dict(os.environ, SOURCE_DATE_EPOCH='0', FORCE_SOURCE_DATE='1', TZ='UTC')
    products = []
    compiler = subprocess.check_output([tools['pdflatex'], '--version'], text=True).splitlines()[0]
    for _ in range(2):
        with tempfile.TemporaryDirectory(prefix='nsc-local-draft-') as directory:
            folder = Path(directory)
            for name, data in files.items():
                (folder / name).write_bytes(data)
            latex = [tools['pdflatex'], '-no-shell-escape', '-interaction=nonstopmode',
                     '-halt-on-error', '-file-line-error', 'main.tex']
            for cmd in (latex, [tools['bibtex'], 'main'], latex, latex):
                run = subprocess.run(cmd, cwd=folder, env=env, capture_output=True, text=True)
                if run.returncode:
                    raise ValueError('TeX build failed: ' + run.stdout[-3500:] + run.stderr[-1000:])
            log = (folder / 'main.log').read_text(errors='replace')
            if re.search(r'(undefined references|undefined citations|Citation .* undefined|Reference .* undefined|Rerun to get)', log):
                raise ValueError('unresolved TeX references')
            if re.search(r'Overfull \\[hv]box', log):
                details = '\n'.join(re.findall(r'Overfull[^\n]*\n(?:[^\n]*\n){0,5}', log))
                raise ValueError('overfull TeX box; inspect layout before delivery:\n' + details)
            products.append(((folder / 'main.pdf').read_bytes(), (folder / 'main.bbl').read_bytes()))
    if products[0] != products[1]:
        raise ValueError('two clean PDF/bibliography builds differ')
    return products[0][0], products[0][1], compiler


def verify(root: Path = ROOT):
    snapshot = authenticate_snapshot(root)
    files = source_files(root)
    manifest = read_json(root / MANIFEST)
    if (manifest['status'] != 'OPEN' or manifest['submission_ready'] is not False
            or manifest['complete_scientific_dependency_closure'] is not False
            or manifest['lab_commit'] != snapshot['lab_commit']):
        raise ValueError('invalid draft manifest')
    expected = {**{(SOURCE / n).as_posix(): digest(b) for n, b in files.items()},
                (EVIDENCE / 'snapshot.json').as_posix(): digest((root / EVIDENCE / 'snapshot.json').read_bytes()),
                'scripts/local_gate_draft.py': digest((root / 'scripts/local_gate_draft.py').read_bytes())}
    if manifest['inputs'] != expected:
        raise ValueError('draft build inputs differ')
    if digest((root / PDF).read_bytes()) != manifest['pdf_sha256']:
        raise ValueError('PDF hash mismatch')
    archive = (root / ARCHIVE).read_bytes()
    if digest(archive) != manifest['source_archive_sha256']:
        raise ValueError('source archive hash mismatch')
    with tarfile.open(fileobj=io.BytesIO(archive), mode='r:gz') as tar:
        members = tar.getmembers()
        if len({m.name for m in members}) != len(members) or any(not m.isfile() for m in members):
            raise ValueError('duplicate or non-file archive member')
        if {m.name for m in members} != set(files) | {'main.bbl'}:
            raise ValueError('source archive inventory differs')
        for m in members:
            data = tar.extractfile(m).read()
            expected_hash = manifest['bbl_sha256'] if m.name == 'main.bbl' else digest(files[m.name])
            if digest(data) != expected_hash:
                raise ValueError('source archive content differs')
    return {'status': 'OPEN', 'submission_ready': False, 'artifact_integrity': 'PASS',
            'lab_commit': snapshot['lab_commit'], 'pdf_sha256': manifest['pdf_sha256'],
            'scope': 'draft bytes and selected evidence; not scientific certificate replay'}
